version: '2'

services:
  web: 
    build: ./server
    container_name: "corpse_app"
    command: npm run dev
    ports:
      - "3000:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
  client:
    build: ./client
    container_name: 'corpse_client'
    volumes:
      - ./client/src:/client/src
    ports:
      - "3001:3000"
  mongodb:
    image: mongo:latest
    container_name: "corpse_mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/Users/wagnerizing/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles 
